- name: Check NGC_KEY is defined as an environment variable
  ansible.builtin.fail:
    msg: >
      NGC_KEY is not defined. Provide your Key with `export NGC_KEY=...`
      If running with sudo, re-run this playbook with `NGC_KEY=... sudo -E ansible-playbook bootstrap.yml`
  when: NGC_KEY is not defined

