- name: Run 'mst start'
  ansible.builtin.shell: mst start

- name: Parse 'mst -v'
  ansible.netcommon.cli_parse:
    command: mst status -v
    parser:
      name: ansible.netcommon.native
      template_path: "{{ role_path }}/templates/mst.yaml"
    set_fact: mst


- name: Show parsed values
  ansible.builtin.debug:
    var: mst
