- name: Print warning 1
  ansible.builtin.debug:
    msg: Running in unsafe mode, DPU may be rebooted
  when: not ( safe | bool )

- name: Run 'mst start'
  ansible.builtin.shell: mst start

- name: Parse 'mst -v'
  ansible.netcommon.cli_parse:
    command: mst status -v
    parser:
      name: ansible.netcommon.native
      template_path: "{{ role_path }}/templates/mst.yaml"
    set_fact: mst

- name: Check DPU mode
  ansible.builtin.shell: "mlxconfig -d {{ mst[ptp_interface]['mst'] }} q | grep -i model"
  register: dpu_mode

- name: Fail if DPU mode is not SEPERATED_HOST
  ansible.builtin.fail:
    msg: >
      Incorrect DPU mode. 
      Please run `sudo mlxconfig -d {{ mst[ptp_interface]['mst'] }} s INTERNAL_CPU_MODEL=0` 
      from the DPU, reboot it and re-run the playbook.
  when: 
  - dpu_mode.stdout.find('SEPERATED_HOST') == -1
  - ( safe | bool )


- name: Change DPU mode
  ansible.builtin.shell: mlxconfig -y -d {{ mst[ptp_interface]['mst'] }} s INTERNAL_CPU_MODEL=0
  when: 
  - dpu_mode.stdout.find('SEPERATED_HOST') == -1
  - not ( safe | bool )

- name: Print warning 2
  ansible.builtin.debug:
    msg: DPU mode changed, rebooting
  when: 
  - dpu_mode.stdout.find('SEPERATED_HOST') == -1
  - not( safe | bool )

- name: Rebooting
  reboot:
    reboot_timeout: 3600
  when: 
  - dpu_mode.stdout.find('SEPERATED_HOST') == -1
  - not ( safe | bool )